name: pull-request-workflow
on:
  pull_request:
    types: [opened]

jobs:
  pull-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "This is a pull request workflow"
      - name: step2
        run : |
          echo "This is a pull request workflow - step2"
          echo "Running multiple commands"